//
//  DummyTempates.swift
//  Tempat List APP
//
//  Created by Aditya Ataby Hidayat on 21/04/21.
// Copyright © 2021 Aditya Ataby Hidayat. All rights reserved
//

import UIKit

let tempates = [Tempat(id: 1, photo: "Pantai_Tanjung_Baru",name: "Pantai Tanjung Baru", description: "Suasana pantai dengan suguhan deburan ombak dan angin sepoi yang menenangkan dapat Anda nikmati disini dengan menyiapkan budget Rp 10.000 per orang untuk tiket masuk, biaya parkir motor Rp 2.000 dan biaya parkir mobil Rp 5.000. Dibuka selama 24 jam dengan waktu tempuh perjalanan sekitar 80 menit dari pusat Kota Karawang. Jarak Pantai Tanjung Baru dengan pusat Kota Karawang kurang lebih 40 km dengan menggunakan kendaraan roda dua maupun roda empat dengan akses jalan yang sudah cukup bagus. Meskipun pasir pantainya berwarna agak kecoklatan dan air lautnya tidak begitu jernih, namun tidak menghilangkan pesona yang dimiliki."),
                
                Tempat(id: 2, photo: "CURUG CIGENTIS",name: "CURUG CIGENTIS", description: "Curug Cigentis berada yang berada di kawasan Gunung Sanggabuana, Kabupaten Karawang. Curug atau Air terjun Cigentis bisa menjadi pilihan Anda yang menyuikai wisata alam khususnya air terjun. Wisata alam yang masih alami di Karawang ini biasanya dijadikan objek wisata bagi trailer atau goweser serta fotografer. Keindahan air terjun dan hutan yang ada di sekelilingnya itulah menyajikan pesona alam nan sejuk dan mententramkan jiwa. Curug Cigentis berada di ketinggian kurang lebih 1000 m di atas permukaan laut (dpl) dan memiliki ketinggian sekitar 25 meter dengan debit air yang dipengaruhi curah hujan turun di atas kawasan tersebut, bila musim kemarau panjang maka airnya seperti air pancuran."),
                
                Tempat(id: 3, photo: "Danau Cipule",name: "Danau Cipule", description: "Danau yang berada di kabupaten Karawang cukup terkenal karena tampilannya yang mirip dengan danau Toba di Sumatera. Danau Cipule berlokasi di tepian Sungai Citarum, tepatnya di Desa Kutapohaci, Kecamatan Ciampel, Kabupaten Karawang, Jawa Barat, sekitar 20 kilometer dari pusat kota Karawang, 3 km dari Bendungan Walahar arah ke Selatan.Namun tak seperti danau Toba, danau Cipule bukanlah danau alami."),
                
                Tempat(id: 4, photo: "Pantai Pelangi",name: "Pantai Pelangi", description: "Melaju sekitar 35 km dari pusat kota Karawang, Anda bisa menemukan Pantai Pelangi yang menawan. Wisata alam satu ini hingga saat ini masih menjadi salah satu wisata yang favorit dikunjungi. Memang waktu yang dibutuhkan tidak sebentar, tetapi medan yang nantinya akan dilalui sudah mudah untuk dijangkau. Apalagi sepanjang perjalanan, Anda akan disajikan dengan hamparan sawah hijau yang menyejukkan mata. Dan pemandangan akan jauh lebih cantik saat Anda tiba di kawasan Pantai Pelangi ini. Ombak pantai satu ini terbilang tenang, sehingga Anda bisa bermain pasir dengan bebas dan tenang. Fasilitas penunjang di pantai Pelangi juga sudah memadai. Alamat: Sungaibuntu, Kec. Pedes, Kab. Karawang, Jawa Barat."),
                
                Tempat(id: 5, photo: "Monumen Kebulatan Tekad Rengasdengklok",name: "Monumen Kebulatan Tekad Rengasdengklok", description: "Monumen Kebulatan Tekad Rengasdengklok. Monumen ini adalah satu tujuan wisata sejarah yang ada di wilayah Karawang.  Monumen ini dibangun di atas tanah seluas 1.500 m2, yang merupakan bekas lokasi markas PETA di Kampung Bojong Tugu, Desa Rengasdengklok Utara, Kecamatan Rengasdengklok.Monumen dibangun  pada tahun 1950."),
                
                Tempat(id: 6, photo: "BENDUNGAN WALAHAR",name: "BENDUNGAN WALAHAR", description: "Kabupaten Karawang adalah sebuah kabupaten di Tatar Pasundan Provinsi Jawa Barat, Indonesia, berbatasan dengan Kabupaten Bekasi dan Kabupaten Bogor di barat, Laut Jawa di utara, Kabupaten Subang di timur, Kabupaten Purwakarta di tenggara, serta Kabupaten Cianjur di selatan. Memiliki luas wilayah 1.737,53 km2, dengan jumlah penduduk 2.125.234 jiwa (sensus 2010).Pentingnya daerah Karawang tidak hanya pada masa Kerajaan Tarumanegara dan masa berkembangnya Islam. Sebagai daerah yang subur sangat wajar bila menarik minat asing untuk datang dan bermukim seperti misalnya pendatang dari Cina dan Eropa. Pada masa kolonial Belanda."),
                
                Tempat(id: 7, photo: "Curug Cipanundaan",name: "Curug Cipanundaan", description: "Curug Cipanundaan berada di kaki Gunung Sanggabuan dengan 3 (tiga) buah Curug jadi satu dalam satu areal seperti tangga, curungan air ditunda dalam kolam kesatu, turun lagi di kolam kedua, turun lagi ditunda dalam kolam ketiga. Air Terjun ini baru ditemukan oleh Masyarakat setempat, dan Expedisi Wisata dengan Ketua Team Drs."),
                
                Tempat(id: 8, photo: "Tugu Rawa Gede ",name: "Tugu Rawa Gede ", description: "Obyek Wisata Tugu Rawa Gede di Rawamerta Kerawang Jawa Barat adalah salah satu tempat wisata yang berada di desa balongsari, kabupaten kerawang, provinsi jawa barat, negara indonesia. Obyek Wisata Tugu Rawa Gede di Rawamerta Kerawang Jawa Barat adalah tempat wisata yang ramai dengan wisatawan pada hari biasa maupun hari liburan. Tempat ini sangat indah dan bisa memberikan sensasi yang berbeda dengan aktivitas kita sehari hari. Obyek Wisata Tugu Rawa Gede di Rawamerta Kerawang Jawa Barat memiliki pesona keindahan yang sangat menarik untuk dikunjungi. Sangat di sayangkan jika anda berada di kota kerawang tidak mengunjungi wisata sejarah yang mempunyai keindahan yang tiada duanya tersebut.Obyek Wisata Tugu Rawa Gede di Rawamerta Kerawang Jawa Barat sangat cocok untuk mengisi kegiatan liburan anda, apalagi saat liburan panjang seperti libur nasional, ataupun hari ibur lainnya. Keindahan Obyek Wisata Tugu Rawa Gede di Rawamerta Kerawang Jawa Barat ini sangatlah baik bagi anda semua yang berada di dekat atau di kejauhan untuk merapat mengunjungi tempat Obyek Wisata Tugu Rawa Gede di Rawamerta Kerawang Jawa Barat di kota kerawang.Daya Tarik Obyek Wisata Tugu Rawa Gede di Rawamerta Kerawang Jawa Barat merupakan tempat wisata yang harus anda kunjungi karena pesona keindahannya tidak ada duanya."),
                
                Tempat(id: 9, photo: "Pantai Samudera Baru krw",name: "Pantai Samudera Baru", description: "Tempat wisata di Karawang yang wajib dikunjungi berikutnya adalah Pantai Samudera Baru. Disini kamu dapat menikmati pantai berpasir putih dengan ombak yang tenang. Lokasi Pantai Samudera Baru terletak di Kecamatan Pedes 30 km dari Ibu Kota Kabupaten Karawang. Bagi kamu yang suka berburu sunset, kamu bisa mengunjungi pantai ini dan berfoto bersama keluarga."),
                
                Tempat(id: 10, photo: "Bahari Mangrove Tangkolak",name: "Bahari Mangrove Tangkolak", description: "Obyek Wisata bahari mangrove tangkolak berada di desa Sukakerta Kecamatan  Cilamaya Wetan. Wisata bahari diving (selam) pulau pasir putih & diving (selam) Karang Sendulang dengan Pendamping Selam pakai Speed Boat dengan jarak tempuh dari pantai selama 10 menit. Jarak dari Karawang Kota deket kok, kira-kira 40 km dengan mobil kurang lebih selama 1 jam 15 menit.")
]
